apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  ports:
    - name: http-app
      port:  80
      protocol: TCP
      targetPort: 80
    - name: https-app
      port:  443
      protocol: TCP
      targetPort: 443
    - name: http-app-mult
      port:  81
      protocol: TCP
      targetPort: 81
  selector:
    app: main